### PR TITLE
use $public_ipv4:6443 for apiservers

### PR DESCRIPTION
**Pull request by doublerr**
Accessing the apiserver via read-only or https
settings must be done via the public interface since
that's where they listen and I don't see a way to move
them to another elsewhere.

The GCE implementation uses the https(port 6443) for
this communication. We'll follow the same pattern but
still need to implement a certificate to be served. Using
the read-only port resulted in "failure to write" errors
which makes sense.

The python fixes were to force python2.7 since those
calls don't work with python3+.

### CODE REVIEW

**Comment by erictune** [comment]
Thanks for the PR.  

I don't think this will work quite right.

I don't think the kubelet or kube-proxy will be able to authenticate to the apiserver on port 6443 because I don't see where the credentials are distributed to them. 

I can see a couple of options:
1.  You can set `--address=$private_ip` on your apiserver so that it serves port 8080 on the ServiceNet.   But this does leave the apiserver open to anyone on the ServiceNet.  
2.  You can setting `--public_address_override=$private_ip` on your apiserver to make port 7080 (and 6443) be exposed on the ServiceNet, but 8080 will stay on localhost.
3.  You can do what you did in this PR, plus also generate a security token and distribute it to the kubelets so they can authenticate themselves to the apiserver.  This is a bit more work, but it is what the other kubernetes distros like GCE do.  I'm happy to explain this in more detail, or you can just `grep -i token -R cluster`.

**Comment by doublerr** [comment]
@erictune Thanks for the feedback. I was following GCE's lead but realized more work is needed to get things to auth. I was presuming that would be part of a larger change coming soon since I need to dig into those pieces.

3) seems like the right direction to go. The question is can we/should we merge these changes now and I'll work on the rest or just hold off?

Ryan

**Comment by erictune** [comment]
I can't take your patch and merge it to Kubernetes without you signing the CLA first.   So, I'm going to hold off work on this PR.

**Comment by doublerr** [comment]
closing this. Will work on updating directly to kubernetes

**Pull request closed without merging**
